
# Global define (Required)
global:
  # Kube version
  kubeVersion: ""

  # Common labels
  commonLabels: {}

  # Common annotations
  commonAnnotations: {}

  # Cluster domain
  clusterDomain: cluster.local

# Full name override
fullnameOverride: code-server

# Name override
nameOverride: code-server

# Namespace override
namespaceOverride:

image:
  # The image registry of the Code Server.
  registry:

  # The image repository of the Code Server.
  repository: linuxserver/code-server

  # The tag of the Code Server image. If not specified the appVersion from Chart.yaml is used as a tag.
  # tag: "4.17.1"
  # The digest of the Code Server image.
  # If digest is specified it has precedence over tag and will be used instead
  # digest: "sha256:CHANGEME"

  # The pull policy for the Code Server image.
  pullPolicy: IfNotPresent

# Annotations for deployment
annotations: {}

selectorLabels: {}

pod:
  # The annotations of the Code Server pod.
  annotations: {}

  # The additional extra labels of the Code Server pod.
  extraLabels: {}

hostPorts:
  # Enables hostPort for the Code Server pods.
  enabled: false

  # The HTTP hostPort configuration for the Code Server pods.
  http: 80

containerPorts:
  # The HTTP containerPort configuration for the Code Server pods.
  http: 8443

# DNS policy for the Code Server pods
dnsPolicy: ClusterFirst

# Share process namespace between containers in the Code Server pod.
shareProcessNamespace: false

# A list of extra ports to expose on the Code Server pod. Follows the conventional Kubernetes yaml syntax for container ports.
extraPorts: []

# The lifecycle of the Code Server pods.
lifecycle: {}

# The node selector for pod assignment for the Code Server pods.
# nodeSelector: {}

# The termination grace period of the Code Server pod.
terminationGracePeriodSeconds: 30

# Enables the Code Server pods to use the host's network namespace.
hostNetwork: false

# The resources of the Code Server pods.
resources:
  requests:
    cpu: 100m
    memory: 128Mi
# limits:
#   cpu: 1
#   memory: 1Gi

# The security context for the Code Server pods.
podSecurityContext:
  # Remove curly brackets before adding values
  {}
  # fsGroup: 0
  # seccompProfile:
  #   type: RuntimeDefault

# The security context for the Code Server containers.
securityContext:
  # Remove curly brackets before adding values
  {}
  # capabilities:
  #   drop:
  #     - ALL
  # add:
  #   - NET_BIND_SERVICE
  # allowPrivilegeEscalation: true
  # readOnlyRootFilesystem: false
  # runAsNonRoot: false
  # runAsUser: 0

# The tolerations of the Code Server pods.
tolerations: []

# The affinity of the Code Server pods.
affinity: {}

# The topology spread constraints of the Code Server pods.
# topologySpreadConstraints: {}

# The PriorityClass of the Code Server pods.
# priorityClassName: ""

# Strategy used to replace old Pods by new ones. .spec.strategy.type can be "Recreate" or "RollingUpdate" for Deployments, and "OnDelete" or "RollingUpdate" for Daemonsets. "RollingUpdate" is the default value.
strategy: {}

# The minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available.
minReadySeconds: 0

# The additional environment variables to be set on the Code Server pods.
extraEnvVars: []
# - name: MY_VAR
#   value: myvalue

# The additional environment config from to be set on the Code Server pods.
extraEnvFrom: []
# - configMapRef:
#   name: MY_CONFIGMAP
# - secretRef:
#   name: MY_SECRET

# The number of replicas of the Code Server deployment.
replicaCount: 1

# Extra containers for the Code Server pods.
extraContainers: []
# - name: container
#   image: busybox:1.34
#   command: ['sh', '-c', 'echo this is a sidecar!']

# Pod disruption budget for the Code Server pods.
podDisruptionBudget:
  # Enables PodDisruptionBudget.
  enabled: false
  # The annotations of the Code Server pod disruption budget.
  annotations: {}
  # The number of Code Server pods that should be available. This is a mutually exclusive setting with "maxUnavailable".
  # minAvailable: 1
  # The number of Code Server pods that can be unavailable. This is a mutually exclusive setting with "minAvailable".
  # maxUnavailable: 1

# Extra volume mounts
extraVolumeMounts: []

# Extra volumes
extraVolumes: []

# Extra args
extraArgs: []

# PUID
uid: 1000

# PGID
pid: 1000

# Allow set empty password
emptyPassword: false

# Password when user from browser
password: ""

# Hashed password (option)
hashedPassword: ""

# Sudo password (sudo ...)
sudoPassword: ""

# Hashed sudo password (option)
hashedSudoPassword: ""

# Proxy domain If this optional variable is set, this domain will be proxied for subdomain proxying. See
# ref: https://github.com/cdr/code-server/blob/master/docs/FAQ.md#sub-domains
proxyDomain: ""

defaultWorkspace: ""

service:
  # Creates a service to expose the Code Server pods.
  create: true

  # The type of service to create for the Code Server.
  type: LoadBalancer

  # The externalTrafficPolicy of the service. The value Local preserves the client source IP.
  externalTrafficPolicy: Local

  # The annotations of the Code Server service.
  annotations: {}

  # The extra labels of the service.
  extraLabels: {}

  # The static IP address for the load balancer. Requires service.type set to LoadBalancer. The cloud provider must support this feature.
  loadBalancerIP: ""

  # The ClusterIP for the Code Server service, autoassigned if not specified.
  clusterIP: ""

  # The list of external IPs for the Code Server service.
  externalIPs: []

  # The IP ranges (CIDR) that are allowed to access the load balancer. Requires service.type set to LoadBalancer. The cloud provider must support this feature.
  loadBalancerSourceRanges:

  # Whether to automatically allocate NodePorts (only for LoadBalancers).
  # allocateLoadBalancerNodePorts: false

  # Dual stack preference.
  # Valid values: SingleStack, PreferDualStack, RequireDualStack
  # ipFamilyPolicy: SingleStack

  # List of IP families assigned to this service.
  # Valid values: IPv4, IPv6
  # ipFamilies:
  #   - IPv6

  # Ports
  httpPort:
    #
    enabled: true

    # The HTTP port of the Code Server service.
    port: 8443

    # The HTTP port on the POD where the Code Server service is running.
    targetPort: 8443

    # The custom NodePort for the HTTP port. Requires service.type set to NodePort or LoadBalancer.
    # nodePort:

  # A list of extra ports to expose through the Code Server service. Follows the conventional Kubernetes yaml syntax for service ports.
  extraPorts: []

# Ingress configuration
ingress:
  # Enable ingress
  enabled: false

  # Annotations
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  # Ingress class name
  ingressClassName: ""

  # Host configuration
  host: ""

  # TLS configuration
  tls: {}

  # Extra rules configuration
  extraRules: []
  # Extra TLSs configuration
  # - host: chart.example
  #   paths:
  #     pathType: ImplementationSpecific
  #     path: /

  extraTls: []
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local

serviceAccount:
  # Specifies whether a service account should be created
  create: true

  # The annotations of the service account of the Code Server pods.
  annotations: {}

  # The name of the service account of the Code Server pods. Used for RBAC.
  # Autogenerated if not set or set to "".
  # name: code-server

  # The name of the secret containing docker registry credentials.
  # Secret must exist in the same namespace as the helm release.
  imagePullSecretName: ""

  # A list of secret names containing docker registry credentials.
  # Secrets must exist in the same namespace as the helm release.
  imagePullSecretsNames: []

  # If you don't want the kubelet to automatically mount a ServiceAccount's API credentials,
  # you can opt out of the default behavior.
  # You can opt out of automounting API credentials on
  # /var/run/secrets/kubernetes.io/serviceaccount/token for a service account by setting automountServiceAccountToken: false on the ServiceAccount:
  automountServiceAccountToken: true

# HorizontalPodAutoscaling (HPA)
autoscaling:
  # Enables HorizontalPodAutoscaling.
  enabled: false

  # The annotations of the Ingress Controller HorizontalPodAutoscaler.
  annotations: {}

  # Minimum number of replicas for the HPA.
  minReplicas: 1

  # Maximum number of replicas for the HPA.
  maxReplicas: 3

  # The target cpu utilization percentage.
  targetCPUUtilizationPercentage: 50

  # The target memory utilization percentage.
  targetMemoryUtilizationPercentage: 50

  # Custom behavior policies
  behavior: {}

# Enable persistence using Persistent Volume Claims
# ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
persistence:
  # Enable persistence using PVC
  enabled: true

  # Annotations are only applied to persistentVolumeClaim
  # annotations:
  #  "helm.sh/resource-policy": keep
  mountPath: "/config"

  subPath: ""

  volumeName: ""

  # If defined, storageClassName: <storageClass>
  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined (the default) or set to null, no storageClassName spec is
  #   set, choosing the default provisioner.  (gp2 on AWS, standard on
  #   GKE, AWS & OpenStack)
  #
  storageClass: "hostpath"

  # Claims use the same conventions as volumes when requesting storage with specific access modes.
  # ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteOnce

  existingClaim: ""

  size: 4Gi

  # Kubernetes supports two volumeModes of PersistentVolumes: Filesystem and Block.

  # volumeMode is an optional API parameter. Filesystem is the default mode used when volumeMode parameter is omitted.

  # A volume with volumeMode: Filesystem is mounted into Pods into a directory.
  # If the volume is backed by a block device and the device is empty,
  # Kubernetes creates a filesystem on the device before mounting it for the first time.
  # ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode
  volumeMode: ""

  # Claims can specify a label selector to further filter the set of volumes.
  # Only the volumes whose labels match the selector can be bound to the claim.
  # The selector can consist of two fields:
  # ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
  # matchLabels:
  #     release: "stable"
  selector: {}

  # This is useful if you want to consume PersistentVolumes that have their persistentVolumeReclaimPolicy set to Retain,
  # including cases where you are reusing an existing PV. (Retain,Recycle,...)
  persistentVolumeReclaimPolicy: ""

  # A hostPath volume mounts a file or directory from the host node's filesystem into your Pod.
  # This is not something that most Pods will need, but it offers a powerful escape hatch for some applications.
  # ref: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
  hostPath:
    path: "/tmp/code"
    type: DirectoryOrCreate

## initContainers Add additional init containers to the pod (evaluated as a template)
##
initContainers: []
