
# Global define (Required)
global:
  # Kube version
  kubeVersion: ""

  # Common labels
  commonLabels: {}

  # Common annotations
  commonAnnotations: {}

  # Cluster domain
  clusterDomain: cluster.local

# Full name override
fullnameOverride: cf-tunnel

# Name override
nameOverride: cf-tunnel

# Namespace override
namespaceOverride:

image:
  # The image registry of the Cloudflare Tunnel.
  registry:

  # The image repository of the Cloudflare Tunnel.
  repository: cloudflare/cloudflared

  # The tag of the Cloudflare Tunnel image.
  # tag: "2025.4.2"
  # The digest of the Cloudflare Tunnel image.
  # If digest is specified it has precedence over tag and will be used instead
  # digest: "sha256:CHANGEME"

  # The pull policy for the Cloudflare Tunnel image.
  pullPolicy: IfNotPresent

# Annotations for deployment
annotations: {}

# Labels for deployment
selectorLabels: {}

pod:
  # The annotations of the Cloudflare Tunnel pod.
  annotations: {}

  # The additional extra labels of the Cloudflare Tunnel pod.
  extraLabels: {}

# DNS policy for the Cloudflare Tunnel pods
dnsPolicy: ClusterFirst

# Share process namespace between containers in the Cloudflare Tunnel pod.
shareProcessNamespace: false

# The lifecycle of the Cloudflare Tunnel pods.
lifecycle: {}

# The node selector for pod assignment for the Cloudflare Tunnel pods.
# nodeSelector: {}

# The termination grace period of the Cloudflare Tunnel pod.
terminationGracePeriodSeconds: 30

# Enables the Cloudflare Tunnel pods to use the host's network namespace.
hostNetwork: false


# The resources of the Cloudflare Tunnel pods.
resources:
  requests:
    cpu: 100m
    memory: 128Mi
# limits:
#   cpu: 1
#   memory: 1Gi

# The security context for the Cloudflare Tunnel pods.
podSecurityContext:
  sysctls:
    - name: net.ipv4.ping_group_range
      value: "65532 65532"
  # Remove curly brackets before adding values
  # {}
  # fsGroup: 0
  # seccompProfile:
  #   type: RuntimeDefault

# The security context for the Cloudflare Tunnel containers.
securityContext:
  # Remove curly brackets before adding values
  {}
  # capabilities:
  #   drop:
  #     - ALL
  # add:
  #   - NET_BIND_SERVICE
  # allowPrivilegeEscalation: true
  # readOnlyRootFilesystem: false
  # runAsNonRoot: false
  # runAsUser: 0

# The tolerations of the Cloudflare Tunnel pods.
tolerations: []

# The affinity of the Cloudflare Tunnel pods.
affinity: {}

# The topology spread constraints of the Cloudflare Tunnel pods.
# topologySpreadConstraints: {}

# The PriorityClass of the Cloudflare Tunnel pods.
# priorityClassName: ""

# Strategy used to replace old Pods by new ones. .spec.strategy.type can be "Recreate" or "RollingUpdate" for Deployments, and "OnDelete" or "RollingUpdate" for Daemonsets. "RollingUpdate" is the default value.
strategy: {}

# The minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available.
minReadySeconds: 0

# The additional environment variables to be set on the Cloudflare Tunnel pods.
extraEnvVars: []
# - name: MY_VAR
#   value: myvalue

# The additional environment config from to be set on the Cloudflare Tunnel pods.
extraEnvFrom: []
# - configMapRef:
#   name: MY_CONFIGMAP
# - secretRef:
#   name: MY_SECRET

# The number of replicas of the Cloudflare Tunnel deployment.
replicaCount: 1


# Extra containers for the Cloudflare Tunnel pods.
extraContainers: []
# - name: container
#   image: busybox:1.34
#   command: ['sh', '-c', 'echo this is a sidecar!']

# Extra args
extraArgs: []

# The liveness probe for the Cloudflare Tunnel.
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  
# initContainers Add additional init containers to the pod (evaluated as a template)
initContainers: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true

  # The annotations of the service account of the Code Server pods.
  annotations: {}

  # The name of the service account of the Code Server pods. Used for RBAC.
  # Autogenerated if not set or set to "".
  # name: code-server

  # The name of the secret containing docker registry credentials.
  # Secret must exist in the same namespace as the helm release.
  imagePullSecretName: ""

  # A list of secret names containing docker registry credentials.
  # Secrets must exist in the same namespace as the helm release.
  imagePullSecretsNames: []

  # If you don't want the kubelet to automatically mount a ServiceAccount's API credentials,
  # you can opt out of the default behavior.
  # You can opt out of automounting API credentials on
  # /var/run/secrets/kubernetes.io/serviceaccount/token for a service account by setting automountServiceAccountToken: false on the ServiceAccount:
  automountServiceAccountToken: true

# HorizontalPodAutoscaling (HPA)
autoscaling:
  # Enables HorizontalPodAutoscaling.
  enabled: false

  # The annotations of the Ingress Controller HorizontalPodAutoscaler.
  annotations: {}

  # Minimum number of replicas for the HPA.
  minReplicas: 1

  # Maximum number of replicas for the HPA.
  maxReplicas: 3

  # The target cpu utilization percentage.
  targetCPUUtilizationPercentage: 50

  # The target memory utilization percentage.
  targetMemoryUtilizationPercentage: 50

  # Custom behavior policies
  behavior: {}

# Cloudflare Tunnel configuration
cloudflared:
  # The token for the Cloudflare Tunnel.
  token: 

  