apiVersion: v2
name: haproxy
description: HAProxy is a free, very fast and reliable reverse-proxy offering high availability, load balancing, and proxying for TCP and HTTP-based applications. It is particularly suited for very high traffic web sites and powers a significant portion of the world's most visited ones.
type: application
version: 0.0.1
appVersion: "3.0.4"
home: https://zeroxsolutions.com
keywords:
  - "haproxy"
  - "community"
  - "helm"
annotations:
  category: "infrastructure"
maintainers:
  - name: ZeroX.
    url: https://github.com/zeroxsolutions/charts
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common