apiVersion: v2
name: gitlab-ce
description: GitLab Community Edition (CE) is an open source end-to-end software development platform with built-in version control, issue tracking, code review, CI/CD, and more.
type: application
version: 0.0.1
appVersion: "16.2.8-ce.0"
home: https://zeroxsolutions.com
keywords:
  - "gitlab"
  - "community"
  - "helm"
annotations:
  category: "infrastructure"
maintainers:
  - name: ZeroX.
    url: https://github.com/zeroxsolutions/charts
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common
  - name: redis-ha
    version: 0.0.1
    repository: file://../redis-ha
    condition: redis-ha.enabled
  - name: postgres-ha
    version: 0.0.1
    repository: file://../postgres-ha
    condition: postgres-ha.enabled