apiVersion: v2
name: postgres
description: PostgreSQL is a powerful, open source object-relational database system with over 35 years of active development that has earned it a strong reputation for reliability, feature robustness, and performance.
icon: file://./icon.png
type: application
version: 0.0.1
appVersion: "14.13"
home: https://zeroxsolutions.com
keywords:
  - "postgres"
  - "database"
  - "helm"
annotations:
  category: "infrastructure"
maintainers:
  - name: ZeroX.
    url: https://github.com/zeroxsolutions/charts
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common