apiVersion: v2
name: common
description: Common library helm charts
type: library
version: 0.0.1
home: https://zeroxsolutions.com
keywords:
  - "common"
  - "library"
  - "template"
annotations:
  category: "infrastructure"
maintainers:
  - name: ZeroX.
    url: https://github.com/zeroxsolutions/charts